AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'config/boot.rb'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/migrate/*'
    - 'spec/features/*'
    - 'spec/support/*.rb'
    - 'spec/support/**/*.rb'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'Rakefile'
    - 'corzinus.gemspec'
  TargetRubyVersion: 2.3

Style/Encoding:
  EnforcedStyle: when_needed
  Enabled: true

Metrics/AbcSize:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/PredicateName:
  Exclude:
    - 'app/models/concerns/addressable_relation.rb'

Documentation:
  Enabled: false


Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
